import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { join, resolve, extname } from 'node:path';
const root = resolve('dist'); const out = process.argv[2]; const w = +process.argv[3]; const sel = process.argv.slice(4);
const types = { '.html': 'text/html', '.css': 'text/css', '.js': 'text/javascript', '.jpg': 'image/jpeg', '.png': 'image/png', '.webp': 'image/webp', '.svg': 'image/svg+xml', '.woff2': 'font/woff2' };
const server = createServer(async (q, r) => { try { let f = join(root, decodeURIComponent(new URL(q.url, 'http://x').pathname)); if ((await stat(f)).isDirectory()) f = join(f, 'index.html'); r.writeHead(200, { 'Content-Type': types[extname(f)] ?? 'application/octet-stream' }); r.end(await readFile(f)); } catch { r.writeHead(404).end(); } });
await new Promise((d) => server.listen(0, '127.0.0.1', d));
const b = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
const p = await b.newPage({ viewport: { width: w, height: 900 } });
await p.goto(`http://127.0.0.1:${server.address().port}/weddings/`, { waitUntil: 'networkidle' });
await p.locator('main img').evaluateAll((imgs) => imgs.forEach((i) => (i.loading = 'eager')));
await p.locator('main img').evaluateAll((imgs) => Promise.all(imgs.map((i) => i.decode())));
await p.addStyleTag({ content: '[class*=floating], .fq, .floating-quote { display:none !important }' });
for (const s of sel) await p.locator(s).first().screenshot({ path: `${out}/${w}-${s.replace(/\W/g, '')}.png` });
await b.close(); server.close();
