/**
 * Central image manifest.
 *
 * Shared page imagery and legacy homepage artwork. Vehicle galleries are
 * imported separately in fleet-images.ts; see docs/fleet-sources.md.
 * The original files in
 * src/assets/photos are DEVELOPMENT PLACEHOLDERS generated by
 * `node scripts/generate-placeholders.mjs` — see scripts/shot-list.mjs for the
 * photography brief and PHOTOGRAPHY.md for the handoff notes.
 *
 * To go live: drop a real photograph over the file of the same name at the same
 * aspect ratio. No component changes are required.
 */
import heroDesktop from '../assets/photos/hero-desktop.jpg';
import heroMobile from '../assets/photos/hero-mobile.jpg';
import fleetClassicTrolley from '../assets/photos/fleet-classic-trolley.png';
import fleetClassicTrolleyInterior from '../assets/photos/fleet-classic-trolley-interior.jpg';
import fleetLimoTrolley from '../assets/photos/fleet-limo-trolley.jpg';
import fleetCoachBus from '../assets/photos/fleet-coach-bus.jpg';
import fleetCoachBusInterior from '../assets/photos/fleet-coach-bus-interior.jpg';
import fleetPartyBus from '../assets/photos/fleet-party-bus.jpg';
import fleetPartyBusInterior from '../assets/photos/fleet-party-bus-interior.jpg';
import fleetLimoVan from '../assets/photos/fleet-limo-van.jpg';
import fleetLimoVanInterior from '../assets/photos/fleet-limo-van-interior.jpg';
import occasions from '../assets/photos/occasions.jpg';
import bannerFleet from '../assets/photos/banner-fleet.jpg';
import bannerWeddings from '../assets/photos/banner-weddings.jpg';
import bannerServices from '../assets/photos/banner-services.jpg';
import bannerContact from '../assets/photos/banner-contact.jpg';
import ogDefault from '../assets/photos/og-default.jpg';

export const photos = {
	heroDesktop,
	heroMobile,
	fleetClassicTrolley,
	fleetClassicTrolleyInterior,
	fleetLimoTrolley,
	fleetCoachBus,
	fleetCoachBusInterior,
	fleetPartyBus,
	fleetPartyBusInterior,
	fleetLimoVan,
	fleetLimoVanInterior,
	occasions,
	bannerFleet,
	bannerWeddings,
	bannerServices,
	bannerContact,
	ogDefault,
};

/**
 * Alt text travels with the image so it stays accurate when the placeholder is
 * replaced by the photograph it describes.
 */
export const alt = {
	heroDesktop:
		'A black Sprinter van, a white trolley and a white coach bus parked side by side on a paver drive beside Geneva Lake at sunset.',
	heroMobile:
		'A white trolley parked on a paver lakeside drive at sunset, with cypress trees, the water and mountains behind.',
	fleetClassicTrolley: 'A white trolley parked on a paver drive, front three-quarter view.',
	fleetClassicTrolleyInterior:
		'Interior of the trolley - varnished wood ceiling, arched windows and bench seating down both sides.',
	fleetLimoTrolley: 'Interior of the limo trolley showing its circular perimeter seating.',
	fleetCoachBus: 'A white coach bus with its luggage bays open, front three-quarter view.',
	fleetCoachBusInterior:
		'Interior of the coach bus - forward-facing reclining seats in tan and brown leather.',
	fleetPartyBus: 'A white party bus waiting at a venue entrance with its door open.',
	fleetPartyBusInterior:
		'Interior of the party bus - quilted black lounge seating around the perimeter under teal accent lighting.',
	fleetLimoVan: 'A black limo van parked on a quiet tree-lined road.',
	fleetLimoVanInterior:
		'Interior of the limo van - quilted black lounge seating under colour-changing accent lighting.',
	occasions:
		'A bride, groom and guests boarding a white trolley on a paver drive beside Geneva Lake.',
	bannerFleet: 'A trolley on a shoreline drive in late afternoon light.',
	bannerWeddings: 'A couple and their wedding party outside a trolley at a lakeside venue.',
	bannerServices: 'A group boarding a coach at a Lake Geneva resort entrance.',
	bannerContact: 'The Geneva Lake waterfront on a calm afternoon.',
	ogDefault: 'Lake Geneva Trolley & Bus Rental — private trolley and bus charters around Geneva Lake.',
} satisfies Record<keyof typeof photos, string>;

/** The hero <img> shows either hero photo depending on screen width, so its alt must fit both. */
export const heroAlt = 'A white trolley parked on a paver drive at sunset, ready for a private charter.';
